[defaults]
ai_model = "minimax/minimax-m2.7"
human_model = "x-ai/grok-4.1-fast"

[models."minimax/minimax-m2.7"]
temperature = 1.1
provider = "auto"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.ai = { max_tokens = 2048 }

[models."x-ai/grok-4.1-fast"]
disabled = true
temperature = 0.9
provider = "auto"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.human = { max_tokens = 180 }

[models."nvidia/openai/gpt-oss-120b"]
temperature = 1.1
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai = { max_tokens = 2048 }

[models."google/gemma-4-31b-it:free"]
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai   = { temperature = 1.1, max_tokens = 2048 }
roles.human = { temperature = 0.9, max_tokens = 180 }

[models."google/gemma-4-26b-a4b-it:free"]
provider = "ai-studio"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.human = { temperature = 0.9, max_tokens = 800 }

[models."google/gemini-3.1-flash-lite"]
provider = "google-vertex"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.ai = { temperature = 1.1, max_tokens = 2048 }

[models."google/gemini-3.1-flash-lite-preview"]
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai = { temperature = 1.1, max_tokens = 2048 }
