[defaults]
ai_model = "deepseek/deepseek-v4-flash"
human_model = "google/gemini-3.1-flash-lite"

[models."minimax/minimax-m2.7"]
temperature = 1.1
provider = "auto"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.ai = { max_tokens = 2048 }

[models."x-ai/grok-4.1-fast"]
disabled = true
temperature = 0.9
provider = "auto"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.human = { max_tokens = 180 }

[models."nvidia/openai/gpt-oss-120b"]
temperature = 1.1
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai = { max_tokens = 2048 }

[models."google/gemma-4-31b-it:free"]
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai   = { temperature = 1.1, max_tokens = 2048 }
roles.human = { temperature = 0.9, max_tokens = 180 }

[models."google/gemma-4-26b-a4b-it:free"]
provider = "ai-studio"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.human = { temperature = 0.9, max_tokens = 800 }

[models."google/gemini-3.1-flash-lite"]
provider = "google-vertex"
reasoning = { effort = "minimal", exclude = false, enable = true }
roles.ai = { temperature = 1.1, max_tokens = 2048 }
roles.human = { provider = "google-direct", temperature = 0.9, max_tokens = 180 }

[models."google/gemini-3.1-flash-lite-preview"]
provider = "auto"
reasoning = { effort = "minimal" }
roles.ai = { temperature = 1.1, max_tokens = 2048 }

[models."google/gemini-3.1-pro-preview"]
provider = "google-vertex"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."google/gemma-4-26b-a4b-it"]
provider = "novita"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."x-ai/grok-4.20"]
provider = "x-ai"
reasoning = { enable = false }

[models."moonshotai/kimi-k2.5"]
provider = "moonshot"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."moonshotai/kimi-k2.6"]
provider = "moonshot"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."deepseek/deepseek-v4-flash"]
provider = "deepseek"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."deepseek/deepseek-v4-flash:free"]
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."tencent/hy3-preview"]
provider = "siliconflow"
reasoning = { effort = "none", enable = false }
tool_choice = false

[models."anthropic/claude-haiku-4.5"]
provider = "anthropic"
reasoning = { enable = false }

[models."arcee-ai/trinity-large-thinking:free"]
provider = "arcee"
reasoning = { effort = "minimal", exclude = false, enable = true }

[models."baidu/cobuddy:free"]
provider = "baidu"
reasoning = { effort = "minimal", exclude = false, enable = true }
